apiVersion: apps/v1
kind: Deployment

metadata:
  # Name of Kubernetes deployment
  name: sentiment-api-deployment

spec:
  # Number of application instances
  replicas: 1

  selector:
    matchLabels:
      app: sentiment-api

  template:
    metadata:
      labels:
        app: sentiment-api

    spec:
      containers:

      # Container settings
      - name: sentiment-api

        # Docker image used for deployment
        image: sentiment-api:latest

        # Uses local image instead of pulling from registry
        imagePullPolicy: Never

        ports:
        # Flask application runs on port 5000
        - containerPort: 5000