apiVersion: v1
kind: Service

metadata:
  # Name of Kubernetes service
  name: sentiment-api-service

spec:
  # Makes app available outside cluster
  type: NodePort

  selector:
    # Connects service to matching pods
    app: sentiment-api

  ports:
    - protocol: TCP

      # Port exposed by the service
      port: 5000

      # Port used inside container
      targetPort: 5000

      # External port on Kubernetes node
      nodePort: 30007