apiVersion: apps/v1
kind: Deployment

metadata:
  name: sentiment-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sentiment-api

  template:
    metadata:
      labels:
        app: sentiment-api

    spec:
      containers:
      - name: sentiment-api
        image: rossatuai/sentiment-api:47
        imagePullPolicy: Always

        ports:
        - containerPort: 5000