apiVersion: apps/v1
kind: Deployment

metadata:
  # Name of Kubernetes deployment
  name: sentiment-api

spec:
  # Number of application instances
  replicas: 2

  selector:
    matchLabels:
      app: sentiment-api

  template:
    metadata:
      labels:
        app: sentiment-api

    spec:
      containers:

      # Container configuration
      - name: sentiment-api


        # Docker image used for deployment
        image: rossatuai/sentiment-api:54
        
        # Always checks for latest image version
        imagePullPolicy: Always

        ports:
        # Container listens on port 5000
        - containerPort: 5000