name: Model Artifact Storage

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python src/train.py

      - name: Debug Files
        run: ls -R

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl

  verify-artifact:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model

      - name: Verify Artifact
        run: ls -R