name: Automatic Retraining

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  retrain:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Validation Data
        run: python src/preprocess.py

      - name: Train Model
        run: python src/train.py

      - name: Run Monitoring and Retraining Script
        run: python src/monitor_and_retrain.py